/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: ["class", '[data-mode="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        inter: ["Inter", "Inter"],
      },
      fontSize: {
        h1: ["22px", "24px"],
        h2: ["19px", "22px"],
        h3: ["16px", "20px"],
        p: ["13px", "18px"],
        caption: ["11px", "16px"],
        caption2: ["9px", "16px"],
      },
      textColor: {
        "surface-base-light": "#F9FAFB",
        "surface-base-dark": "#0E121A",
        "surface-overlay-light": "#FFFFFF",
        "surface-overlay-dark": "#111928",
        "surface-alt-light": "#F3F4F6",
        "surface-alt-dark": "#1F2A37",
        "surface-divider-light": "#E5E7EB",
        "surface-divider-dark": "#1F2A37",
        "action-hover-light": "#1119280A",
        "action-hover-dark": "#FFFFFF0F",
        "action-select-light": "#1119280F",
        "action-select-dark": "#FFFFFF1A",
        "content-primary-light": "#111928",
        "content-primary-dark": "#F3F4F6",
        "content-secondary-light": "#6B7280",
        "content-secondary-dark": "#6B7280",
        "content-tetriary-light": "#9CA3AF",
        "content-tetriary-dark": "#4B5563",
        "accent-light": "#1C64F2",
        "accent-dark": "#3F83F8",
        "success-light": "#057A55",
        "success-dark": "#0E9F6E",
        "error-light": "#E02424",
        "error-dark": "#F05252",
        "progress-light": "#E3A008",
        "progress-dark": "#FACA15",
      },
      backgroundColor: {
        "surface-base-light": "#F9FAFB",
        "surface-base-dark": "#0E121A",
        "surface-overlay-light": "#FFFFFF",
        "surface-overlay-dark": "#111928",
        "surface-alt-light": "#F3F4F6",
        "surface-alt-dark": "#1F2A37",
        "surface-divider-light": "#E5E7EB",
        "surface-divider-dark": "#1F2A37",
        "action-hover-light": "#1119280A",
        "action-hover-dark": "#FFFFFF0F",
        "action-select-light": "#1119280F",
        "action-select-dark": "#FFFFFF1A",
        "content-primary-light": "#111928",
        "content-primary-dark": "#F3F4F6",
        "content-secondary-light": "#6B7280",
        "content-secondary-dark": "#6B7280",
        "content-tetriary-light": "#9CA3AF",
        "content-tetriary-dark": "#4B5563",
        "accent-light": "#1C64F2",
        "accent-dark": "#3F83F8",
        "success-light": "#057A55",
        "success-dark": "#0E9F6E",
        "error-light": "#E02424",
        "error-dark": "#F05252",
        "progress-light": "#E3A008",
        "progress-dark": "#FACA15",
      },
      ringColor: {
        "surface-divider-light": "#E5E7EB",
        "surface-divider-dark": "#1F2A37",
      },
    },
  },
  plugins: [],
};
